// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuvgGISktA1n-zc0cXpA9qIv7BybH0-Io',
    appId: '1:649225477977:android:8f84290e0daff87b213648',
    messagingSenderId: '649225477977',
    projectId: 'offyaba-fa53f',
    storageBucket: 'offyaba-fa53f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvgGISktA1n-zc0cXpA9qIv7BybH0-Io',
    appId: '1:649225477977:ios:58e5f3044930eb00213648',
    messagingSenderId: '649225477977',
    projectId: 'offyaba-fa53f',
    storageBucket: 'offyaba-fa53f.firebasestorage.app',
    iosBundleId: 'com.example.offYaba',
  );

  // this for back-end for web
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDuvgGISktA1n-zc0cXpA9qIv7BybH0-Io",
      authDomain: "offyaba-fa53f.firebaseapp.com",
      projectId: "offyaba-fa53f",
      storageBucket: "offyaba-fa53f.firebasestorage.app",
      messagingSenderId: "649225477977",
      appId: "1:649225477977:web:2a6efa355ca95729213648",
      measurementId: "G-HRYN363ZTP");
}
